Repository InformedSolutions/JAQU-CAZ-Payments-UI, pull requests merged in 2019-11, with the labels that each got.

#70 [CAZ-1333] Redirect to compliant page when vehicle is exempted
  app/controllers/vehicles_controller.rb
  app/models/vehicle_details.rb
  spec/models/vehicle_details_spec.rb
  spec/requests/vehicles_controller/details_spec.rb
  spec/requests/vehicles_controller/submit_details_spec.rb
Labels: bug

#69 [NT] Refactoring related components scss
  app/javascript/styles/related_components.scss
Labels: documentation

#72 [CAZ-1139] Refactoring error summary and add to choose type, non dvla and unrecognised pages
  app/views/charges/local_authority.html.haml
  app/views/common/_error_summary.html.haml
  app/views/dates/daily_charge.html.haml
  app/views/dates/select_daily_date.html.haml
  app/views/dates/select_period.html.haml
  app/views/dates/select_period_input/_errored.html.haml
  app/views/dates/select_weekly_date.html.haml
  app/views/dates/weekly_charge.html.haml
  app/views/non_dvla_vehicles/choose_type.html.haml
  app/views/non_dvla_vehicles/index.html.haml
  app/views/vehicles/details.html.haml
  app/views/vehicles/unrecognised.html.haml
  features/vehicles.feature
Labels: bug

#73 [CAZ-1317] Fix payment for link on review payment page
  app/controllers/charges_controller.rb
  app/helpers/application_helper.rb
  app/views/charges/review_payment.html.haml
  app/views/dates/select_daily_date.html.haml
  features/charges.feature
  features/step_definitions/charges_steps.rb
  features/step_definitions/path_expectations.rb
  features/support/session_helper.rb
Labels: bug

#74 [CAZ-1317] Fix payment for link on review payment page
  app/helpers/application_helper.rb
  app/views/dates/select_daily_date.html.haml
  features/charges.feature
  features/step_definitions/path_expectations.rb
Labels: bug

#81 [CAZ-1488] Add Basic AUTH
  .env.example
  .github/PULL_REQUEST_TEMPLATE
  .rubocop.yml
  app/api_wrapper/api_exception.rb
  app/api_wrapper/compliance_checker_api.rb
  app/controllers/application_controller.rb
  app/javascript/packs/application.js
  app/javascript/src/cookiesBanner/init.js
  app/javascript/src/cookiesBanner/styles.scss
  app/javascript/src/printLink/init.js
  app/javascript/src/printLink/styles.scss
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_google_analytics.html.erb
  app/views/layouts/application.html.haml
  app/views/payments/success.html.haml
  config/application.rb
  config/environments/production.rb
  config/initializers/content_security_policy.rb
  config/webpack/environment.js
Labels: improvement

#86 [CAZ-1443] Fix back button
  app/views/vehicles/compliant.html.haml
Labels: bug

#85 [CAZ-1435] Сonnect Non-UK charge flow with compliance checker API
  app/api_wrapper/compliance_checker_api.rb
  app/api_wrapper/mock_cazes_for_nonuk_response.rb
  app/api_wrapper/mock_compliance_response.rb
  app/controllers/application_controller.rb
  app/controllers/charges_controller.rb
  app/controllers/dates_controller.rb
  app/models/compliance_details.rb
  app/services/chargeable_zones_service.rb
  app/services/vehicle_types.rb
  features/charges.feature
  features/step_definitions/charges_steps.rb
  features/step_definitions/non_uk_vehicles_steps.rb
  features/step_definitions/payments_steps.rb
  features/step_definitions/taxi_steps.rb
  features/step_definitions/vehicle_steps.rb
  features/support/mock_helper.rb
  spec/fixtures/files/unrecognised_response.json
  spec/models/compliance_details_spec.rb
  spec/requests/charges_controller/local_authority_spec.rb
  spec/services/chargeable_zones_service_spec.rb
  spec/services/vehicle_types_spec.rb
Labels: improvement

#88 [CAZ-1490] Update start page content
  app/views/welcome/index.html.haml
Labels: improvement

#91 [CAZ-1443] Fix back button on exempt page
  app/controllers/application_controller.rb
  app/controllers/charges_controller.rb
  app/controllers/payments_controller.rb
  app/controllers/vehicles_controller.rb
  app/views/vehicles/_compliant_and_exempt.html.haml
  app/views/vehicles/compliant.html.haml
  app/views/vehicles/exempt.html.haml
  config/routes.rb
  features/step_definitions/vehicle_steps.rb
  features/support/mock_helper.rb
  features/vehicles.feature
  sonar-project.properties
  spec/fixtures/files/vehicle_details_exempt_response.json
  spec/requests/vehicles_controller/details_spec.rb
  spec/requests/vehicles_controller/exempt_spec.rb
Labels: bug

#92 [CAZ-1492] Update ruby version to 2.6.5
  .rubocop.yml
  .ruby-version
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  README.md
  package.json
  yarn.lock
Labels: enhancement

#97 [NT] Fix rubocop warning
  app/services/vehicle_types.rb
Labels: bug

#93 [CAZ-1495] Add CSP policy
  config/initializers/content_security_policy.rb
  config/initializers/session_store.rb
  yarn.lock
Labels: enhancement

#101 [CAZ-1498] Fix pa11y tests
  app/views/charges/local_authority.html.haml
  app/views/dates/daily_charge.html.haml
  app/views/dates/select_daily_date.html.haml
  app/views/dates/select_period.html.haml
  app/views/dates/select_weekly_date.html.haml
  app/views/dates/weekly_charge.html.haml
  app/views/non_dvla_vehicles/choose_type.html.haml
  app/views/non_dvla_vehicles/index.html.haml
  app/views/vehicles/details.html.haml
  app/views/vehicles/enter_details.html.haml
  app/views/vehicles/unrecognised.html.haml
Labels: bug

#105 [NT] Add health endpoint and skip basic auth
  app/controllers/application_controller.rb
  config/routes.rb
Labels: enhancement
