Repository InformedSolutions/JAQU-CAZ-Payments-UI, pull requests merged in 2020-03, with the labels that each got.

#199 [NT] Update puma version to fix vulnerability warning
  Gemfile.lock
  package.json
  yarn.lock
Labels: improvement

#200 [CAZB-641] Content change to NTR Cookie Policy
  Gemfile
  Gemfile.lock
  app/views/cookies/_cookie_control.html.haml
  app/views/cookies/_ga.html.haml
  app/views/cookies/_session.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_cookie_control.html.erb
Labels: improvement

#198 CAZ-2054 Feature/caz 2054/prod drone changes
  .drone.yml
Labels: do not merge

#203 [CAZB-641] `Accept all cookies` button enabled GA cookies by default
  app/views/layouts/_cookie_control.html.erb
Labels: improvement

#204 [CAZB-742] Hide Control Cookie buttons and add `Save and close` button
  app/views/layouts/_cookie_control.html.erb
  pa11y/.pa11yci.conf.js
Labels: improvement

#206 [NT] Fix Cookie Control black button
  app/javascript/packs/application.js
  app/javascript/src/cookieControl.js
Labels: bug

#207 [NT] Remove `screen capture` from pa11y tests
  pa11y/.pa11yci.conf.js
Labels: bug

#209 [NT] Add temporary exclude to yarn audit
  .drone.yml
Labels: bug

#210 [CAZB-705-706] Fix back button for static pages
  app/controllers/accessibility_controller.rb
  app/controllers/application_controller.rb
  app/controllers/cookies_controller.rb
  app/controllers/policies_controller.rb
  app/controllers/static_pages_controller.rb
  app/views/layouts/_footer.html.haml
  app/views/static_pages/accessibility_statement.html.haml
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/cookies/_cookie_control.html.haml
  app/views/static_pages/cookies/_ga.html.haml
  app/views/static_pages/cookies/_session.html.haml
  app/views/static_pages/cookies/_table_head.html.haml
  app/views/static_pages/privacy_notice.html.haml
  config/routes.rb
  features/accessibility.feature
  features/cookies.feature
  features/privacy_notice.feature
  features/static_pages.feature
  features/step_definitions/helper_steps.rb
  features/step_definitions/path_expectations.rb
  spec/requests/cookies_controller_spec.rb
  spec/requests/policies_controller_spec.rb
  spec/requests/static_pages_spec.rb
  spec/support/shared_examples/static_page.rb
Labels: improvement

#212 Remove require `logstash-logger` from production.rb
  config/environments/production.rb
Labels: bug

#214 Fix print link on success page
  app/javascript/packs/application.js
  app/javascript/src/printLink/init.js
  app/javascript/src/printLink/styles.scss
  app/views/common/_print_link.haml
Labels: bug
