Repository InformedSolutions/JAQU-CAZ-Payments-UI, pull requests merged in 2020-06, with the labels that each got.

#285 Fix drone prod deploy step
  .drone.yml
Labels: bug

#286 Fix drone prod deploy step (#285)
  .drone.yml
Labels: release, release/v1.1.1

#296 [CAZ-2798] Not show Today or another day selection page if future wee…
  app/controllers/dates_controller.rb
  app/services/dates/weekly.rb
  features/step_definitions/taxi_steps.rb
  features/taxi.feature
Labels: bug

#301 Bump ruby version to 2.6.6
  .rubocop.yml
  .ruby-version
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  README.md
  app/helpers/dates_helper.rb
Labels: improvement

#300 [CAZ-2798] Update error message on `Today or another day` selection page
  app/controllers/dates_controller.rb
  app/views/dates/select_weekly_period.html.haml
  app/views/dates/select_weekly_period_input/_errored.html.haml
  config/locales/en.yml
Labels: improvement

#302 Bump rails version to 6.0.3.2
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: improvement

#303 [CAZ-2909] Update D-Day notice
  app/services/dates/base.rb
  app/views/dates/_details.html.haml
  app/views/dates/_weekly_details.html.haml
  app/views/dates/daily/_details.html.haml
  app/views/dates/select_daily_date.html.haml
  app/views/dates/select_weekly_date.html.haml
  features/charges.feature
  features/taxi.feature
  spec/services/dates/daily_spec.rb
  spec/services/dates/weekly_spec.rb
Labels: improvement

#305 [CAZ-2860 | CAZ-2861] Detect possible fraud flow
  app/controllers/charges_controller.rb
  app/controllers/non_dvla_vehicles_controller.rb
  app/controllers/vehicles_controller.rb
  app/models/confirmation_form.rb
  app/models/vrn_form.rb
  app/services/session_manipulation/add_vrn.rb
  app/services/session_manipulation/base_manipulator.rb
  app/services/session_manipulation/set_possible_fraud.rb
  app/views/vehicles/incorrect_details.html.haml
  app/views/vehicles/not_determined.html.haml
  app/views/vehicles/uk_registered_details.html.haml
  config/routes.rb
  features/step_definitions/vehicle_steps.rb
  features/support/mock_helper.rb
  features/vehicles.feature
  spec/models/vrn_form_spec.rb
  spec/requests/vehicles_controller/confirm_uk_registered_details_spec.rb
  spec/requests/vehicles_controller/uk_registered_details_spec.rb
  spec/services/session_manipulation/add_vrn_spec.rb
  spec/services/session_manipulation/set_possible_fraud_spec.rb
  spec/support/add_to_session.rb
Labels: do not merge

#309 [CAZB-1778] Add GTM scripts
  .env.example
  Gemfile.lock
  app/views/layouts/_gtm_noscript.html.erb
  app/views/layouts/_gtm_script.html.erb
  app/views/layouts/application.html.haml
  config/initializers/content_security_policy.rb
Labels: dependencies

#304 [CAZ-2846] Leeds Taxi Weekly Selection - Javascript enabled
  app/controllers/dates_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/datePicker.js
  app/javascript/src/ie11Helpers.js
  app/javascript/styles/application.scss
  app/javascript/styles/datepicker.scss
  app/services/dates/validate_selected_weekly_date.rb
  app/views/dates/select_weekly_date.html.haml
  app/views/dates/select_weekly_date_input/_normal.html.haml
  config/locales/en.yml
  config/webpack/environment.js
  features/charges.feature
  features/taxi.feature
  package.json
  spec/requests/dates_controller/confirm_date_weekly_spec.rb
  spec/services/dates/validate_selected_weekly_date_spec.rb
  spec/support/shared_examples/invalid_weekly_selection_date.rb
  yarn.lock
Labels: improvement
