Repository InformedSolutions/JAQU-CAZ-Payments-UI, pull requests merged in 2020-02, with the labels that each got.

#180 Added tests for ending payment journey if no more dates can be paid for
  features/charges.feature
  features/step_definitions/charges_steps.rb
Labels: improvement

#184 [NT] Convert charge in pence
  app/models/payment.rb
  spec/models/payment_spec.rb
Labels: bug

#185 [NT] Fix pa11y test
  pa11y/.pa11yci.conf.js
Labels: bug

#189 [NT] Rename application.scss to application.css
  app/assets/stylesheets/application.css
Labels: improvement

#193 [CAZB-557] Add cookie control
  .rubocop.yml
  Gemfile.lock
  app/javascript/packs/application.js
  app/javascript/packs/google_analytics.js
  app/javascript/src/cookiesBanner/init.js
  app/javascript/src/cookiesBanner/styles.scss
  app/javascript/styles/application.scss
  app/javascript/styles/cookie_control.scss
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_google_analytics.html.erb
  app/views/layouts/application.html.haml
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
Labels: enhancement

#194 [CAZB-585] Update cookies page
  app/views/cookies/_cookie_control.html.haml
  app/views/cookies/_seen_message.html.haml
  app/views/cookies/index.html.haml
Labels: improvement

#195 [NT] Fix pa11y test
  pa11y/.pa11yci.conf.js
Labels: improvement
