Repository InformedSolutions/JAQU-CAZ-Payments-UI, pull requests merged in 2021-02, with the labels that each got.

#545 [CAZB-2830, 2870] Update content
  app/api_wrapper/base_api.rb
  app/views/non_dvla_vehicles/index.html.haml
  app/views/vehicles/incorrect_details.html.haml
Labels: bug

#537 Promote Payments v1.7.0 to Production
  .drone2.yml
  Gemfile.lock
  additional_url.yml
  app/api_wrapper/base_api.rb
  app/controllers/application_controller.rb
  app/controllers/charges_controller.rb
  app/views/payments/failure.html.haml
  config/environments/test.rb
  spec/requests/charges_controller/local_authority_spec.rb
  spec/requests/charges_controller/review_payment_spec.rb
  spec/requests/charges_controller/submit_local_authority_spec.rb
  spec/requests/dates_controller/select_weekly_date_spec.rb
  spec/requests/dates_controller/select_weekly_period_spec.rb
  spec/requests/non_dvla_vehicles_controller/choose_type_spec.rb
  spec/requests/payments_controller/create_spec.rb
  spec/requests/payments_controller/failure_spec.rb
  spec/requests/payments_controller/index_spec.rb
  spec/requests/payments_controller/success_spec.rb
  spec/requests/vehicles_controller/confirm_details_spec.rb
  spec/requests/vehicles_controller/incorrect_details_spec.rb
  spec/requests/welcome_controller_spec.rb
  spec/spec_helper.rb
  spec/support/add_to_session.rb
Labels: IOD v1.7.0, release

#551 [CAZB-4063] Migrate pipeline to Terraform v0.12.23
  .drone2.yml
Labels: bug

#552 Promote release v1.7.1 to pre-production
  .drone2.yml
Labels: release, release/v1.7.1

#558 Promote Payments v1.7.2 to Production
  .drone2.yml
Labels: IOD v1.7.2, release
