Repository InformedSolutions/JAQU-CAZ-Payments-UI, pull requests merged in 2021-01, with the labels that each got.

#525 [CAZB-3726] Update page title
  app/controllers/vehicles_controller.rb
  app/views/vehicles/_compliant_and_exempt.html.haml
  app/views/vehicles/compliant.html.haml
  app/views/vehicles/exempt.html.haml
  app/views/vehicles/incorrect_details.html.haml
  app/views/vehicles/not_determined.html.haml
  app/views/vehicles/uk_registered_details.html.haml
  features/vehicles.feature
Labels: improvement

#528 [CAZB-3903] Amend content to Accessibility Statement page
  app/views/static_pages/accessibility_statement.html.haml
Labels: improvement

#531 [CAZB-2868] Vehicle not found - change to refund wording
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/views/vehicles/unrecognised.html.haml
  config/application.rb
  package.json
  spec/models/compliance_details_spec.rb
  spec/models/confirmation_form_spec.rb
  spec/models/payment_details_spec.rb
  spec/models/payment_spec.rb
  spec/models/payment_status_spec.rb
  spec/requests/charges_controller/local_authority_spec.rb
  spec/requests/charges_controller/review_payment_spec.rb
  spec/requests/charges_controller/submit_local_authority_spec.rb
  spec/requests/dates_controller/confirm_daily_charge_spec.rb
  spec/requests/dates_controller/confirm_date_weekly_spec.rb
  spec/requests/dates_controller/confirm_second_date_weekly_spec.rb
  spec/requests/dates_controller/confirm_select_daily_date_spec.rb
  spec/requests/dates_controller/confirm_select_weekly_period_spec.rb
  spec/requests/dates_controller/daily_charges_spec.rb
  spec/requests/dates_controller/weekly_charges_spec.rb
  spec/requests/errors_controller_spec.rb
  spec/requests/non_dvla_vehicles_controller/index_spec.rb
  spec/requests/payments_controller/create_spec.rb
  spec/requests/static_pages_controller_spec.rb
  spec/services/chargeable_zones_service_spec.rb
  spec/services/dates/assign_back_button_date_spec.rb
  spec/services/dates/check_paid_daily_spec.rb
  spec/services/dates/check_paid_weekly_spec.rb
  spec/services/dates/daily_spec.rb
  spec/services/dates/validate_selected_weekly_date_spec.rb
  spec/services/dates/weekly_spec.rb
  spec/services/fetch_single_caz_data_spec.rb
  spec/services/session_manipulation/set_compliance_details_spec.rb
  spec/services/session_manipulation/set_confirm_weekly_charge_today_spec.rb
  spec/services/session_manipulation/set_payment_details_spec.rb
  spec/support/shared_examples/chareable_zones_service.rb
  spec/support/shared_examples/invalid_weekly_selection_date.rb
  spec/support/shared_examples/unsuccessful_call.rb
  yarn.lock
Labels: improvement

#532 [CAZB-2868] Fix deploy - Vehicle not found - change to refund wording
  config/environments/production.rb
Labels: bug

#533 [CAZB-2868] Vehicle not found - change to refund wording
  app/views/vehicles/unrecognised.html.haml
Labels: improvement

#535 Promote Payments v1.7.0 to Pre-Prod
  .drone2.yml
  Gemfile.lock
  additional_url.yml
  app/api_wrapper/base_api.rb
  app/controllers/application_controller.rb
  app/controllers/charges_controller.rb
  app/views/payments/failure.html.haml
  config/environments/test.rb
  spec/requests/charges_controller/local_authority_spec.rb
  spec/requests/charges_controller/review_payment_spec.rb
  spec/requests/charges_controller/submit_local_authority_spec.rb
  spec/requests/dates_controller/select_weekly_date_spec.rb
  spec/requests/dates_controller/select_weekly_period_spec.rb
  spec/requests/non_dvla_vehicles_controller/choose_type_spec.rb
  spec/requests/payments_controller/create_spec.rb
  spec/requests/payments_controller/failure_spec.rb
  spec/requests/payments_controller/index_spec.rb
  spec/requests/payments_controller/success_spec.rb
  spec/requests/vehicles_controller/confirm_details_spec.rb
  spec/requests/vehicles_controller/incorrect_details_spec.rb
  spec/requests/welcome_controller_spec.rb
  spec/spec_helper.rb
  spec/support/add_to_session.rb
Labels: IOD v1.7.0, release
