Repository InformedSolutions/JAQU-CAZ-Payments-UI, pull requests merged in 2021-05, with the labels that each got.

#645 Promote Payments v2.3.0 to Production
  .drone2.yml
  .rubocop.yml
  .ruby-version
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/charges_controller.rb
  app/controllers/non_dvla_vehicles_controller.rb
  app/controllers/vehicles_controller.rb
  app/controllers/welcome_controller.rb
  app/models/vehicle_details.rb
  app/models/vrn_form.rb
  app/services/chargeable_zones_service.rb
  app/services/dates/weekly.rb
  config/database.yml
  config/initializers/backtrace_silencers.rb
  config/initializers/content_security_policy.rb
  config/initializers/inflections.rb
  config/initializers/mime_types.rb
  config/initializers/webpacker.rb
  config/routes.rb
  db/seeds.rb
  lib/assets/.keep
  lib/tasks/.keep
  package.json
  spec/api_wrappers/compliance_checker_api/clean_air_zones_spec.rb
  spec/api_wrappers/compliance_checker_api/register_details_spec.rb
  spec/api_wrappers/compliance_checker_api/unrecognised_compliance_spec.rb
  spec/api_wrappers/compliance_checker_api/vehicle_details_spec.rb
  spec/api_wrappers/payments_api/create_payment_spec.rb
  spec/api_wrappers/payments_api/paid_payments_dates_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/models/payment_spec.rb
  spec/models/vehicle_details_spec.rb
  spec/models/vrn_form_spec.rb
  spec/requests/dates_controller/daily_charges_spec.rb
  spec/requests/dates_controller/select_second_weekly_date_spec.rb
  spec/requests/dates_controller/select_weekly_date_spec.rb
  spec/requests/dates_controller/weekly_charges_spec.rb
  spec/requests/payments_controller/create_spec.rb
  spec/requests/vehicles_controller/enter_details_spec.rb
  spec/services/chargeable_zones_service_spec.rb
  spec/services/dates/check_paid_daily_spec.rb
  spec/services/dates/check_paid_weekly_spec.rb
  spec/services/dates/daily_spec.rb
  spec/services/dates/weekly_spec.rb
  spec/services/session_manipulation/clear_session_details_spec.rb
  spec/spec_helper.rb
  storage/.keep
  vendor/.keep
  yarn.lock
Labels: IOD v2.3.0, dont merge yet, release

#659 [CAZB-4771] Use instance methods in `CazDataProvider` class
  .dockerignore
  .drone2.yml
  .gitignore
  .iyarc
  .scss-lint.yml
  .stylelintrc.json
  Gemfile
  Gemfile.lock
  README.md
  additional_url.yml
  app/controllers/dates_controller.rb
  app/controllers/static_pages_controller.rb
  app/javascript/packs/application.js
  app/javascript/src/govukFrontendAssets.js
  app/javascript/src/printLink/styles.scss
  app/javascript/styles/application.scss
  app/javascript/styles/cookie-control.scss
  app/javascript/styles/datepicker.scss
  app/javascript/styles/govuk-frontend.scss
  app/javascript/styles/related-components.scss
  app/services/caz_data_provider.rb
  app/services/dates/review_weekly_selection.rb
  ci-cd-resources/check_build_number.sh
  ci-cd-resources/jmeter/PAYMENT-UI-TEST-Latest.jmx
  ci-cd-resources/jmeter/assertion.yml
  ci-cd-resources/pa11y/.pa11yci.conf.js
  ci-cd-resources/pa11y/Dockerfile
  ci-cd-resources/pa11y/Makefile
  config/brakeman.ignore
  config/database.yml
  features/step_definitions/charges_steps.rb
  features/step_definitions/taxi_steps.rb
  features/support/mock_helper.rb
  features/support/session_helper.rb
  package.json
  spec/requests/charges_controller/review_payment_spec.rb
  spec/requests/dates_controller/confirm_date_weekly_spec.rb
  spec/requests/dates_controller/confirm_second_date_weekly_spec.rb
  spec/requests/dates_controller/select_daily_date_spec.rb
  spec/requests/dates_controller/select_second_weekly_date_spec.rb
  spec/requests/dates_controller/select_weekly_date_spec.rb
  spec/services/caz_data_provider_spec.rb
  spec/services/dates/review_weekly_selection_spec.rb
  spec/support/add_to_session.rb
  spec/support/api_mocks.rb
  yarn.lock
Labels: improvement

#660 Fix accessibility tests
  .drone2.yml
Labels: bug
